### PR TITLE
Reverse move problem

### PR DESCRIPTION
**Pull request by r2k-in-the-vortex**
did not work if q1 < q0, negative move implemented, more detailed example added

image

### CODE REVIEW

**Comment by r2k-in-the-vortex** [comment]
extended support for negative move for shorter ranges

image

noticed that short moves with no time for constant acceleration produce minor glitches

image

**Comment by r2k-in-the-vortex** [comment]
ahah, understood, the reason for constant acceleration time "glitches" is recursive algorithm that approaches proper max_acceleration value. Probably not a real problem.

**Comment by r2k-in-the-vortex** [comment]
fixes for non zero v0 when moving negative direction

image

image

**Comment by r2k-in-the-vortex** [comment]
tests and fixes also for non-zero v1 conditions

image

**Comment by r2k-in-the-vortex** [comment]
codecov added to have better idea about what is tested and what is not. seems reasonable, few things need work

https://app.codecov.io/github/r2k-in-the-vortex/s_curve/blob/reverse_move_problem/src/lib.rs

**Comment by r2k-in-the-vortex** [comment]
Eh... yeah there are merge commits there so that doesn't squash after the fact, at least github gives me an error on that. What I'm going to do is put the combined changes on a different branch and open up a different PR, that's nice and clean, I agree, the history of me wrangling CI is not needed for anyone.

**Comment by enomado** [comment]
Use the `--force`, Luke

**Pull request closed without merging**
